package com.barryku.cloud.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * Notification Service Implementation
 *
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-10T15:51:30.132-07:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "NotificationService", 
                  wsdlLocation = "classpath:/sforce.wsdl",
                  targetNamespace = "http://soap.sforce.com/2005/09/outbound") 
public class NotificationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.sforce.com/2005/09/outbound", "NotificationService");
    public final static QName Notification = new QName("http://soap.sforce.com/2005/09/outbound", "Notification");
    static {
        URL url = NotificationService.class.getClassLoader().getResource("/sforce.wsdl");
        if (url == null) {
            url = NotificationService.class.getClassLoader().getResource("sforce.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(NotificationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:/sforce.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public NotificationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NotificationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns NotificationPort
     */
    @WebEndpoint(name = "Notification")
    public NotificationPort getNotification() {
        return super.getPort(Notification, NotificationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationPort
     */
    @WebEndpoint(name = "Notification")
    public NotificationPort getNotification(WebServiceFeature... features) {
        return super.getPort(Notification, NotificationPort.class, features);
    }

}
