
package com.barryku.cloud.cxf;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-10T15:51:30.125-07:00
 * Generated source version: 2.4.2
 * 
 */
 
public class NotificationPort_Notification_Server{

    protected NotificationPort_Notification_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new NotificationPortImpl();
        String address = "http://localhost/53w5";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new NotificationPort_Notification_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
