
package com.barryku.cloud.sforce.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-11T16:54:21.678-07:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "InvalidQueryLocatorFault", targetNamespace = "urn:fault.partner.soap.sforce.com")
public class InvalidQueryLocatorFault_Exception extends Exception {
    
    private com.barryku.cloud.sforce.partner.InvalidQueryLocatorFault invalidQueryLocatorFault;

    public InvalidQueryLocatorFault_Exception() {
        super();
    }
    
    public InvalidQueryLocatorFault_Exception(String message) {
        super(message);
    }
    
    public InvalidQueryLocatorFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidQueryLocatorFault_Exception(String message, com.barryku.cloud.sforce.partner.InvalidQueryLocatorFault invalidQueryLocatorFault) {
        super(message);
        this.invalidQueryLocatorFault = invalidQueryLocatorFault;
    }

    public InvalidQueryLocatorFault_Exception(String message, com.barryku.cloud.sforce.partner.InvalidQueryLocatorFault invalidQueryLocatorFault, Throwable cause) {
        super(message, cause);
        this.invalidQueryLocatorFault = invalidQueryLocatorFault;
    }

    public com.barryku.cloud.sforce.partner.InvalidQueryLocatorFault getFaultInfo() {
        return this.invalidQueryLocatorFault;
    }
}
