
package com.barryku.cloud.sforce.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-11T16:54:21.603-07:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "InvalidIdFault", targetNamespace = "urn:fault.partner.soap.sforce.com")
public class InvalidIdFault_Exception extends Exception {
    
    private com.barryku.cloud.sforce.partner.InvalidIdFault invalidIdFault;

    public InvalidIdFault_Exception() {
        super();
    }
    
    public InvalidIdFault_Exception(String message) {
        super(message);
    }
    
    public InvalidIdFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidIdFault_Exception(String message, com.barryku.cloud.sforce.partner.InvalidIdFault invalidIdFault) {
        super(message);
        this.invalidIdFault = invalidIdFault;
    }

    public InvalidIdFault_Exception(String message, com.barryku.cloud.sforce.partner.InvalidIdFault invalidIdFault, Throwable cause) {
        super(message, cause);
        this.invalidIdFault = invalidIdFault;
    }

    public com.barryku.cloud.sforce.partner.InvalidIdFault getFaultInfo() {
        return this.invalidIdFault;
    }
}
