
package com.barryku.cloud.sforce.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-11T16:54:21.577-07:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "InvalidSObjectFault", targetNamespace = "urn:fault.partner.soap.sforce.com")
public class InvalidSObjectFault_Exception extends Exception {
    
    private com.barryku.cloud.sforce.partner.InvalidSObjectFault invalidSObjectFault;

    public InvalidSObjectFault_Exception() {
        super();
    }
    
    public InvalidSObjectFault_Exception(String message) {
        super(message);
    }
    
    public InvalidSObjectFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidSObjectFault_Exception(String message, com.barryku.cloud.sforce.partner.InvalidSObjectFault invalidSObjectFault) {
        super(message);
        this.invalidSObjectFault = invalidSObjectFault;
    }

    public InvalidSObjectFault_Exception(String message, com.barryku.cloud.sforce.partner.InvalidSObjectFault invalidSObjectFault, Throwable cause) {
        super(message, cause);
        this.invalidSObjectFault = invalidSObjectFault;
    }

    public com.barryku.cloud.sforce.partner.InvalidSObjectFault getFaultInfo() {
        return this.invalidSObjectFault;
    }
}
