
package com.barryku.cloud.sforce.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-11T16:54:21.699-07:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "MalformedSearchFault", targetNamespace = "urn:fault.partner.soap.sforce.com")
public class MalformedSearchFault_Exception extends Exception {
    
    private com.barryku.cloud.sforce.partner.MalformedSearchFault malformedSearchFault;

    public MalformedSearchFault_Exception() {
        super();
    }
    
    public MalformedSearchFault_Exception(String message) {
        super(message);
    }
    
    public MalformedSearchFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MalformedSearchFault_Exception(String message, com.barryku.cloud.sforce.partner.MalformedSearchFault malformedSearchFault) {
        super(message);
        this.malformedSearchFault = malformedSearchFault;
    }

    public MalformedSearchFault_Exception(String message, com.barryku.cloud.sforce.partner.MalformedSearchFault malformedSearchFault, Throwable cause) {
        super(message, cause);
        this.malformedSearchFault = malformedSearchFault;
    }

    public com.barryku.cloud.sforce.partner.MalformedSearchFault getFaultInfo() {
        return this.malformedSearchFault;
    }
}
