
package com.barryku.cloud.sforce.partner;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-11T16:54:21.417-07:00
 * Generated source version: 2.4.2
 * 
 */
public final class Soap_Soap_Client {

    private static final QName SERVICE_NAME = new QName("urn:partner.soap.sforce.com", "SforceService");

    private Soap_Soap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SforceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SforceService ss = new SforceService(wsdlURL, SERVICE_NAME);
        Soap port = ss.getSoap();  
        
        {
        System.out.println("Invoking merge...");
        java.util.List<com.barryku.cloud.sforce.partner.MergeRequest> _merge_request = null;
        try {
            java.util.List<com.barryku.cloud.sforce.partner.MergeResult> _merge__return = port.merge(_merge_request);
            System.out.println("merge.result=" + _merge__return);

        } catch (InvalidFieldFault_Exception e) { 
            System.out.println("Expected exception: InvalidFieldFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidSObjectFault_Exception e) { 
            System.out.println("Expected exception: InvalidSObjectFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidIdFault_Exception e) { 
            System.out.println("Expected exception: InvalidIdFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getUserInfo...");
        try {
            com.barryku.cloud.sforce.partner.GetUserInfoResult _getUserInfo__return = port.getUserInfo();
            System.out.println("getUserInfo.result=" + _getUserInfo__return);

        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking describeSoftphoneLayout...");
        try {
            com.barryku.cloud.sforce.partner.DescribeSoftphoneLayoutResult _describeSoftphoneLayout__return = port.describeSoftphoneLayout();
            System.out.println("describeSoftphoneLayout.result=" + _describeSoftphoneLayout__return);

        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking update...");
        java.util.List<com.barryku.cloud.sforce.partner.SObject> _update_sObjects = null;
        try {
            java.util.List<com.barryku.cloud.sforce.partner.SaveResult> _update__return = port.update(_update_sObjects);
            System.out.println("update.result=" + _update__return);

        } catch (InvalidFieldFault_Exception e) { 
            System.out.println("Expected exception: InvalidFieldFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidSObjectFault_Exception e) { 
            System.out.println("Expected exception: InvalidSObjectFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidIdFault_Exception e) { 
            System.out.println("Expected exception: InvalidIdFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking setPassword...");
        java.lang.String _setPassword_userId = "";
        java.lang.String _setPassword_password = "";
        try {
            com.barryku.cloud.sforce.partner.SetPasswordResult _setPassword__return = port.setPassword(_setPassword_userId, _setPassword_password);
            System.out.println("setPassword.result=" + _setPassword__return);

        } catch (InvalidNewPasswordFault_Exception e) { 
            System.out.println("Expected exception: InvalidNewPasswordFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidIdFault_Exception e) { 
            System.out.println("Expected exception: InvalidIdFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking logout...");
        try {
            port.logout();

        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking retrieve...");
        java.lang.String _retrieve_fieldList = "";
        java.lang.String _retrieve_sObjectType = "";
        java.util.List<java.lang.String> _retrieve_ids = null;
        try {
            java.util.List<com.barryku.cloud.sforce.partner.SObject> _retrieve__return = port.retrieve(_retrieve_fieldList, _retrieve_sObjectType, _retrieve_ids);
            System.out.println("retrieve.result=" + _retrieve__return);

        } catch (InvalidFieldFault_Exception e) { 
            System.out.println("Expected exception: InvalidFieldFault has occurred.");
            System.out.println(e.toString());
        } catch (MalformedQueryFault_Exception e) { 
            System.out.println("Expected exception: MalformedQueryFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidSObjectFault_Exception e) { 
            System.out.println("Expected exception: InvalidSObjectFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidIdFault_Exception e) { 
            System.out.println("Expected exception: InvalidIdFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking queryAll...");
        java.lang.String _queryAll_queryString = "";
        try {
            com.barryku.cloud.sforce.partner.QueryResult _queryAll__return = port.queryAll(_queryAll_queryString);
            System.out.println("queryAll.result=" + _queryAll__return);

        } catch (InvalidFieldFault_Exception e) { 
            System.out.println("Expected exception: InvalidFieldFault has occurred.");
            System.out.println(e.toString());
        } catch (MalformedQueryFault_Exception e) { 
            System.out.println("Expected exception: MalformedQueryFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidSObjectFault_Exception e) { 
            System.out.println("Expected exception: InvalidSObjectFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidIdFault_Exception e) { 
            System.out.println("Expected exception: InvalidIdFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidQueryLocatorFault_Exception e) { 
            System.out.println("Expected exception: InvalidQueryLocatorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getUpdated...");
        java.lang.String _getUpdated_sObjectType = "";
        javax.xml.datatype.XMLGregorianCalendar _getUpdated_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getUpdated_endDate = null;
        try {
            com.barryku.cloud.sforce.partner.GetUpdatedResult _getUpdated__return = port.getUpdated(_getUpdated_sObjectType, _getUpdated_startDate, _getUpdated_endDate);
            System.out.println("getUpdated.result=" + _getUpdated__return);

        } catch (InvalidSObjectFault_Exception e) { 
            System.out.println("Expected exception: InvalidSObjectFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking undelete...");
        java.util.List<java.lang.String> _undelete_ids = null;
        try {
            java.util.List<com.barryku.cloud.sforce.partner.UndeleteResult> _undelete__return = port.undelete(_undelete_ids);
            System.out.println("undelete.result=" + _undelete__return);

        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking create...");
        java.util.List<com.barryku.cloud.sforce.partner.SObject> _create_sObjects = null;
        try {
            java.util.List<com.barryku.cloud.sforce.partner.SaveResult> _create__return = port.create(_create_sObjects);
            System.out.println("create.result=" + _create__return);

        } catch (InvalidFieldFault_Exception e) { 
            System.out.println("Expected exception: InvalidFieldFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidSObjectFault_Exception e) { 
            System.out.println("Expected exception: InvalidSObjectFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidIdFault_Exception e) { 
            System.out.println("Expected exception: InvalidIdFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking sendEmail...");
        java.util.List<com.barryku.cloud.sforce.partner.Email> _sendEmail_messages = null;
        try {
            java.util.List<com.barryku.cloud.sforce.partner.SendEmailResult> _sendEmail__return = port.sendEmail(_sendEmail_messages);
            System.out.println("sendEmail.result=" + _sendEmail__return);

        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking search...");
        java.lang.String _search_searchString = "";
        try {
            com.barryku.cloud.sforce.partner.SearchResult _search__return = port.search(_search_searchString);
            System.out.println("search.result=" + _search__return);

        } catch (InvalidFieldFault_Exception e) { 
            System.out.println("Expected exception: InvalidFieldFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidSObjectFault_Exception e) { 
            System.out.println("Expected exception: InvalidSObjectFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        } catch (MalformedSearchFault_Exception e) { 
            System.out.println("Expected exception: MalformedSearchFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking query...");
        java.lang.String _query_queryString = "";
        try {
            com.barryku.cloud.sforce.partner.QueryResult _query__return = port.query(_query_queryString);
            System.out.println("query.result=" + _query__return);

        } catch (InvalidFieldFault_Exception e) { 
            System.out.println("Expected exception: InvalidFieldFault has occurred.");
            System.out.println(e.toString());
        } catch (MalformedQueryFault_Exception e) { 
            System.out.println("Expected exception: MalformedQueryFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidSObjectFault_Exception e) { 
            System.out.println("Expected exception: InvalidSObjectFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidIdFault_Exception e) { 
            System.out.println("Expected exception: InvalidIdFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidQueryLocatorFault_Exception e) { 
            System.out.println("Expected exception: InvalidQueryLocatorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getDeleted...");
        java.lang.String _getDeleted_sObjectType = "";
        javax.xml.datatype.XMLGregorianCalendar _getDeleted_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getDeleted_endDate = null;
        try {
            com.barryku.cloud.sforce.partner.GetDeletedResult _getDeleted__return = port.getDeleted(_getDeleted_sObjectType, _getDeleted_startDate, _getDeleted_endDate);
            System.out.println("getDeleted.result=" + _getDeleted__return);

        } catch (InvalidSObjectFault_Exception e) { 
            System.out.println("Expected exception: InvalidSObjectFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking process...");
        java.util.List<com.barryku.cloud.sforce.partner.ProcessRequest> _process_actions = null;
        try {
            java.util.List<com.barryku.cloud.sforce.partner.ProcessResult> _process__return = port.process(_process_actions);
            System.out.println("process.result=" + _process__return);

        } catch (InvalidIdFault_Exception e) { 
            System.out.println("Expected exception: InvalidIdFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking describeDataCategoryGroupStructures...");
        java.util.List<com.barryku.cloud.sforce.partner.DataCategoryGroupSobjectTypePair> _describeDataCategoryGroupStructures_pairs = null;
        boolean _describeDataCategoryGroupStructures_topCategoriesOnly = false;
        try {
            java.util.List<com.barryku.cloud.sforce.partner.DescribeDataCategoryGroupStructureResult> _describeDataCategoryGroupStructures__return = port.describeDataCategoryGroupStructures(_describeDataCategoryGroupStructures_pairs, _describeDataCategoryGroupStructures_topCategoriesOnly);
            System.out.println("describeDataCategoryGroupStructures.result=" + _describeDataCategoryGroupStructures__return);

        } catch (InvalidSObjectFault_Exception e) { 
            System.out.println("Expected exception: InvalidSObjectFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking resetPassword...");
        java.lang.String _resetPassword_userId = "";
        try {
            com.barryku.cloud.sforce.partner.ResetPasswordResult _resetPassword__return = port.resetPassword(_resetPassword_userId);
            System.out.println("resetPassword.result=" + _resetPassword__return);

        } catch (InvalidIdFault_Exception e) { 
            System.out.println("Expected exception: InvalidIdFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking describeGlobal...");
        try {
            com.barryku.cloud.sforce.partner.DescribeGlobalResult _describeGlobal__return = port.describeGlobal();
            System.out.println("describeGlobal.result=" + _describeGlobal__return);

        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking describeLayout...");
        com.barryku.cloud.sforce.partner.DescribeLayout2 _describeLayout_parameters = null;
        try {
            com.barryku.cloud.sforce.partner.DescribeLayoutResponse _describeLayout__return = port.describeLayout(_describeLayout_parameters);
            System.out.println("describeLayout.result=" + _describeLayout__return);

        } catch (InvalidSObjectFault_Exception e) { 
            System.out.println("Expected exception: InvalidSObjectFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidIdFault_Exception e) { 
            System.out.println("Expected exception: InvalidIdFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking describeTabs...");
        try {
            java.util.List<com.barryku.cloud.sforce.partner.DescribeTabSetResult> _describeTabs__return = port.describeTabs();
            System.out.println("describeTabs.result=" + _describeTabs__return);

        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking describeDataCategoryGroups...");
        java.util.List<java.lang.String> _describeDataCategoryGroups_sObjectType = null;
        try {
            java.util.List<com.barryku.cloud.sforce.partner.DescribeDataCategoryGroupResult> _describeDataCategoryGroups__return = port.describeDataCategoryGroups(_describeDataCategoryGroups_sObjectType);
            System.out.println("describeDataCategoryGroups.result=" + _describeDataCategoryGroups__return);

        } catch (InvalidSObjectFault_Exception e) { 
            System.out.println("Expected exception: InvalidSObjectFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getServerTimestamp...");
        try {
            com.barryku.cloud.sforce.partner.GetServerTimestampResult _getServerTimestamp__return = port.getServerTimestamp();
            System.out.println("getServerTimestamp.result=" + _getServerTimestamp__return);

        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking invalidateSessions...");
        java.util.List<java.lang.String> _invalidateSessions_sessionIds = null;
        try {
            java.util.List<com.barryku.cloud.sforce.partner.InvalidateSessionsResult> _invalidateSessions__return = port.invalidateSessions(_invalidateSessions_sessionIds);
            System.out.println("invalidateSessions.result=" + _invalidateSessions__return);

        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking describeSObject...");
        java.lang.String _describeSObject_sObjectType = "";
        try {
            com.barryku.cloud.sforce.partner.DescribeSObjectResult _describeSObject__return = port.describeSObject(_describeSObject_sObjectType);
            System.out.println("describeSObject.result=" + _describeSObject__return);

        } catch (InvalidSObjectFault_Exception e) { 
            System.out.println("Expected exception: InvalidSObjectFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking login...");
        java.lang.String _login_username = "";
        java.lang.String _login_password = "";
        try {
            com.barryku.cloud.sforce.partner.LoginResult _login__return = port.login(_login_username, _login_password);
            System.out.println("login.result=" + _login__return);

        } catch (LoginFault_Exception e) { 
            System.out.println("Expected exception: LoginFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidIdFault_Exception e) { 
            System.out.println("Expected exception: InvalidIdFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking queryMore...");
        java.lang.String _queryMore_queryLocator = "";
        try {
            com.barryku.cloud.sforce.partner.QueryResult _queryMore__return = port.queryMore(_queryMore_queryLocator);
            System.out.println("queryMore.result=" + _queryMore__return);

        } catch (InvalidFieldFault_Exception e) { 
            System.out.println("Expected exception: InvalidFieldFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidQueryLocatorFault_Exception e) { 
            System.out.println("Expected exception: InvalidQueryLocatorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking describeSObjects...");
        java.util.List<java.lang.String> _describeSObjects_sObjectType = null;
        try {
            java.util.List<com.barryku.cloud.sforce.partner.DescribeSObjectResult> _describeSObjects__return = port.describeSObjects(_describeSObjects_sObjectType);
            System.out.println("describeSObjects.result=" + _describeSObjects__return);

        } catch (InvalidSObjectFault_Exception e) { 
            System.out.println("Expected exception: InvalidSObjectFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking emptyRecycleBin...");
        java.util.List<java.lang.String> _emptyRecycleBin_ids = null;
        try {
            java.util.List<com.barryku.cloud.sforce.partner.EmptyRecycleBinResult> _emptyRecycleBin__return = port.emptyRecycleBin(_emptyRecycleBin_ids);
            System.out.println("emptyRecycleBin.result=" + _emptyRecycleBin__return);

        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking upsert...");
        java.lang.String _upsert_externalIDFieldName = "";
        java.util.List<com.barryku.cloud.sforce.partner.SObject> _upsert_sObjects = null;
        try {
            java.util.List<com.barryku.cloud.sforce.partner.UpsertResult> _upsert__return = port.upsert(_upsert_externalIDFieldName, _upsert_sObjects);
            System.out.println("upsert.result=" + _upsert__return);

        } catch (InvalidFieldFault_Exception e) { 
            System.out.println("Expected exception: InvalidFieldFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidSObjectFault_Exception e) { 
            System.out.println("Expected exception: InvalidSObjectFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidIdFault_Exception e) { 
            System.out.println("Expected exception: InvalidIdFault has occurred.");
            System.out.println(e.toString());
        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking convertLead...");
        java.util.List<com.barryku.cloud.sforce.partner.LeadConvert> _convertLead_leadConverts = null;
        try {
            java.util.List<com.barryku.cloud.sforce.partner.LeadConvertResult> _convertLead__return = port.convertLead(_convertLead_leadConverts);
            System.out.println("convertLead.result=" + _convertLead__return);

        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking delete...");
        java.util.List<java.lang.String> _delete_ids = null;
        try {
            java.util.List<com.barryku.cloud.sforce.partner.DeleteResult> _delete__return = port.delete(_delete_ids);
            System.out.println("delete.result=" + _delete__return);

        } catch (UnexpectedErrorFault_Exception e) { 
            System.out.println("Expected exception: UnexpectedErrorFault has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
